version: "3.6"
services:

  certificatemanagement:
    image: "nager/nager-certificatemanagement:latest"
    environment:
      LETSENCRYPT__EMAIL: 
      LETSENCRYPT__REQUESTMODE: TEST
      DNSPROVIDER__HETZNER__APIKEY: 
      DNSPROVIDER__CLOUDFLARE__APIKEY: 
      ASPNETCORE_ENVIRONMENT: Development
      OBJECTSTORAGE__ENDPOINT: http://minio:9000
      OBJECTSTORAGE__ACCESSKEY: AKIAIOSFODNN7EXAMPLE
      OBJECTSTORAGE__SECRETKEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    ports:
      - 80:80
    depends_on:
      - minio

  minio:
    image: "minio/minio"
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
